name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: bot-paper-artifacts
          path: 'paper/build/libs/*.jar'

      - uses: actions/upload-artifact@v4
        with:
          name: bot-fabric-artifacts
          path: 'fabric/build/libs/*.jar'
